language: c

dist: bionic
sudo: false

# apparently apt addon doesn't work on bionic?
before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential gcc-multilib g++-multilib clang cmake ninja-build libc6-dbg:i386 tcc valgrind

script: test/unit/ci-unix.sh

compiler:
  - clang
  - gcc
  - tcc
  - scan-build

env:
  - AMALGAMATED=1
  - STANDARD=1

matrix:
  include:

    # code coverage build
    - os: linux
      compiler: gcov
      env: "STANDARD=1"
      before_install:
        - sudo apt-get update
        # these packages are needed for urllib3[secure] for SNI support for
        # coveralls integration
        - sudo apt-get install -y python-dev libffi-dev libssl-dev
        # the rest of this is copied from above
        - sudo apt-get install -y build-essential gcc-multilib g++-multilib clang cmake ninja-build libc6-dbg:i386 tcc valgrind
